import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@/src/apollo/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Toaster />
        </body>
      </ApolloProvider>
    </html>
  );
}
